# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_verifycodemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='avater/', verbose_name='头像'),
        ),
    ]
