# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180122_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
