# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180125_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, default='', help_text='类别描述', null=True, verbose_name='类别描述'),
        ),
    ]
