# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180125_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tittle',
            field=models.CharField(help_text='标题', max_length=100, verbose_name='标题'),
        ),
    ]
