# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentblog',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='commentblog',
            name='comment',
        ),
        migrations.DeleteModel(
            name='CommentBlog',
        ),
    ]
